### ISSUE TITLE
能去掉 openapi:7.0.3 的引用吗

### ISSUE THREAD

**Issue by yindalei00** [dueros/bot-sdk-java#4]
能去掉 openapi:7.0.3 的引用吗，我看到监控 里面 只使用  一个 方法，这个包 10M +++ 
1.0.2 版本中 开始加入的  这个包的，
<dependency>
            <groupId>com.intellij</groupId>
            <artifactId>openapi</artifactId>

**Comment by longger** [comment]
下个版本会解决一下这个问题
