### ISSUE TITLE
Certificate的构造类里面有bug

### ISSUE THREAD

**Issue by delonzhou** [dueros/bot-sdk-java#7]
版本：1.1.1

1. 下面的request的header key "signature"首字母应为大写的
2. 下面的request的header key "signaturecerturl"首字母应为大写的
3. 获取上述两个key的逻辑应该是不对，感觉是乱写的

public Certificate(HttpServletRequest request) {
        try {
            Map<String, String> map = new HashMap();
            Enumeration headernames = request.getHeaderNames();

            String signature;
            String signaturecerturl;
            while(headernames.hasMoreElements()) {
                signature = (String)headernames.nextElement();
                signaturecerturl = request.getHeader(signature);
                map.put(signature, signaturecerturl);
            }

            signature = (String)map.get("signature");
            signaturecerturl = (String)map.get("signaturecerturl");
            BufferedReader bufferedReader = new BufferedReader(new InputStreamReader(request.getInputStream(), "utf-8"));
            StringBuffer stringBuffer = new StringBuffer("");
            String temp = "";

            while((temp = bufferedReader.readLine()) != null) {
                stringBuffer.append(temp);
            }

            String message = stringBuffer.toString();
            this.signature = signature;
            this.signaturecerturl = signaturecerturl;
            this.message = message;
        } catch (IOException var10) {
            ;
        }

    }

**Comment by longger** [comment]
HTTP协议的Header的key是大小写不敏感的
